package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"shifty-backend/graph/model"
)

// CreatePosition is the resolver for the createPosition field.
func (r *mutationResolver) CreatePosition(ctx context.Context, input model.CreatePositionInput) (*model.Position, error) {
	panic(fmt.Errorf("not implemented: CreatePosition - createPosition"))
}

// UpdatePosition is the resolver for the updatePosition field.
func (r *mutationResolver) UpdatePosition(ctx context.Context, input model.UpdatePositionInput) (*model.Position, error) {
	panic(fmt.Errorf("not implemented: UpdatePosition - updatePosition"))
}

// DeletePosition is the resolver for the deletePosition field.
func (r *mutationResolver) DeletePosition(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePosition - deletePosition"))
}

// Position is the resolver for the position field.
func (r *queryResolver) Position(ctx context.Context, id string) (*model.Position, error) {
	panic(fmt.Errorf("not implemented: Position - position"))
}

// PositionsByRestaurant is the resolver for the positionsByRestaurant field.
func (r *queryResolver) PositionsByRestaurant(ctx context.Context, restaurantID string) ([]*model.Position, error) {
	panic(fmt.Errorf("not implemented: PositionsByRestaurant - positionsByRestaurant"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
