package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateRestaurant is the resolver for the createRestaurant field.
func (r *mutationResolver) CreateRestaurant(ctx context.Context, input model.CreateRestaurantInput) (*model.Restaurant, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	mapRestaurant := MapRestaurantModelToEntity(&input)

	newRestaurant, err := r.RestaurantUseCase.Create(ctx, userID, mapRestaurant)

	if err != nil {
		return nil, err
	}

	return MapRestaurantEntityToModel(newRestaurant), nil
}

// UpdateRestaurant is the resolver for the updateRestaurant field.
func (r *mutationResolver) UpdateRestaurant(ctx context.Context, input model.UpdateRestaurantInput) (*model.Restaurant, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := MapRestaurantUpdateToMap(&input)

	if err != nil {
		return nil, xerror.Internal("Can not map restaurant data")
	}

	updatedRestaurant, err := r.RestaurantUseCase.Update(ctx, userID, input.RestaurantID, updateData)

	if err != nil {
		return nil, err
	}

	return MapRestaurantEntityToModel(updatedRestaurant), nil
}

// CreateInviteCode is the resolver for the createInviteCode field.
func (r *mutationResolver) CreateInviteCode(ctx context.Context, input model.CreateInviteCodeInput) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.RestaurantUseCase.CreateInviteCode(ctx, userID, input.Email, input.ResID, input.PositionID)

	if err != nil {
		return false, err
	}

	return true, nil
}

// JoinRestaurant is the resolver for the joinRestaurant field.
func (r *mutationResolver) JoinRestaurant(ctx context.Context, input model.JoinRestaurantInput) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.RestaurantUseCase.JoinRestaurant(ctx, userID, input.InviteCode)
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteRestaurant is the resolver for the deleteRestaurant field.
func (r *mutationResolver) DeleteRestaurant(ctx context.Context, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	if err := r.RestaurantUseCase.Delete(ctx, userID, resID); err != nil {
		return false, err
	}

	return true, nil
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, resID string) (*model.Restaurant, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	restaurant, err := r.RestaurantUseCase.GetByID(ctx, userID, resID)

	if err != nil {
		return nil, err
	}

	mapRestaurant := MapRestaurantEntityToModel(restaurant)

	return mapRestaurant, nil
}

// MyRestaurants is the resolver for the myRestaurants field.
func (r *queryResolver) MyRestaurants(ctx context.Context) ([]*model.Restaurant, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	restaurants, err := r.RestaurantUseCase.GetMyRestaurants(ctx, userID)
	if err != nil {
		return nil, err
	}
	myRestaurants := make([]*model.Restaurant, 0, len(restaurants))

	for _, restaurant := range restaurants {
		mappedRestaurant := MapRestaurantEntityToModel(restaurant)
		myRestaurants = append(myRestaurants, mappedRestaurant)
	}
	return myRestaurants, nil
}
