package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"shifty-backend/graph/model"
)

// CreateRestaurant is the resolver for the createRestaurant field.
func (r *mutationResolver) CreateRestaurant(ctx context.Context, input model.CreateRestaurantInput) (*model.Restaurant, error) {
	panic(fmt.Errorf("not implemented: CreateRestaurant - createRestaurant"))
}

// UpdateRestaurant is the resolver for the updateRestaurant field.
func (r *mutationResolver) UpdateRestaurant(ctx context.Context, input model.UpdateRestaurantInput) (*model.Restaurant, error) {
	panic(fmt.Errorf("not implemented: UpdateRestaurant - updateRestaurant"))
}

// DeleteRestaurant is the resolver for the deleteRestaurant field.
func (r *mutationResolver) DeleteRestaurant(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRestaurant - deleteRestaurant"))
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*model.Restaurant, error) {
	panic(fmt.Errorf("not implemented: Restaurant - restaurant"))
}

// MyRestaurants is the resolver for the myRestaurants field.
func (r *queryResolver) MyRestaurants(ctx context.Context) ([]*model.Restaurant, error) {
	panic(fmt.Errorf("not implemented: MyRestaurants - myRestaurants"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
