package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"shifty-backend/graph/model"
	"shifty-backend/internal/dto"
	"shifty-backend/pkg/xerror"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input *model.UpdateUserInput) (*model.User, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	// Map updateuserinput to entity
	userEntity := MapUserUpdateInputToEntity(userID, input)

	// Call usecase to update
	updatedUser, err := r.UserUseCase.UpdateUser(ctx, userEntity)

	if err != nil {
		return nil, err
	}

	// Return back with map user fro entity to model
	return MapUserEntityToModel(updatedUser), nil
}

// UpdateStaffByManager is the resolver for the updateStaffByManager field.
func (r *mutationResolver) UpdateStaffByManager(ctx context.Context, input *model.UpdateStaffByManagerInput) (*model.UserRestaurant, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	if input.Restaurant == nil || input.StaffID == nil {
		return nil, xerror.BadRequest("Restaurant ID and Staff ID are required")
	}
	updateData, err := MapStaffUpdateToMap(input)
	if err != nil {
		return nil, err
	}

	updatedStaff, err := r.UserRestaurantUseCase.UpdateStaffByManager(ctx, userID, *input.StaffID, *input.Restaurant, updateData)

	if err != nil {
		return nil, err
	}

	return MapUserRestaurantEntityToModel(updatedStaff), nil
}

// Delete is the resolver for the delete field.
func (r *mutationResolver) Delete(ctx context.Context) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	// Call usecase for delete user
	if err := r.UserUseCase.DeleteUser(ctx, userID); err != nil {
		return false, err
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	user, err := r.UserUseCase.FindUserByID(ctx, userID)

	if err != nil {
		return nil, err
	}
	var jobs []*model.UserJob
	for _, contract := range user.UserRestaurants {
		jobs = append(jobs, &model.UserJob{
			RestaurantID:   contract.RestaurantID.String(),
			RestaurantName: contract.Restaurant.Name,
			Position:       contract.Position.Name,
		})
	}
	return &model.User{
		ID:          user.ID.String(),
		FullName:    user.FullName,
		Email:       user.Email,
		PhoneNumber: user.PhoneNumber,
		Avatar:      user.Avatar,
		Address:     user.Address,
		Role:        string(user.Role),
		Jobs:        jobs,
		CreatedAt:   user.CreatedAt,
	}, nil
}

// RestaurantMembers is the resolver for the restaurantMembers field.
func (r *queryResolver) RestaurantMembers(ctx context.Context, restaurantID string, limit *int, page *int, filter *model.UserFilterInput) (*model.UserPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	p := 1
	if page != nil {
		p = *page
	}
	l := 10
	if limit != nil {
		l = *limit
	}
	var filterDTO *dto.UserFilter
	if filter != nil {
		filterDTO = &dto.UserFilter{
			Search:   filter.Search,
			Position: filter.Position,
		}
	}
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	isValid, err := r.UserUseCase.ValidateRestaurantAccess(ctx, userID, restaurantID)

	if err != nil {
		return nil, err
	}
	if !isValid {
		return nil, xerror.BadRequest("You are not member of this restaurant")
	}

	users, total, err := r.UserUseCase.GetRestaurantMembers(ctx, p, l, restaurantID, filterDTO)
	if err != nil {
		return nil, err
	}

	listUserModels := make([]*model.User, 0, len(users))
	for _, u := range users {
		var jobs []*model.UserJob
		if len(u.UserRestaurants) > 0 {
			contract := u.UserRestaurants[0]

			jobs = append(jobs, &model.UserJob{
				RestaurantID:   contract.Restaurant.ID.String(),
				RestaurantName: contract.Restaurant.Name,
				Position:       contract.Position.Name,
			})
		}
		listUserModels = append(listUserModels, &model.User{
			ID:          u.ID.String(),
			FullName:    u.FullName,
			Email:       u.Email,
			Role:        string(u.Role),
			Avatar:      u.Avatar,
			PhoneNumber: u.PhoneNumber,
			Address:     u.Address,
			Jobs:        jobs,
			CreatedAt:   u.CreatedAt,
		})
	}
	totalPages := 0
	if l > 0 {
		totalPages = int((total + int64(l) - 1) / int64(l))
	}

	return &model.UserPagination{
		Data:        listUserModels,
		CurrentPage: p,
		TotalPages:  totalPages,
		Total:       int(total),
	}, nil
}
