package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	commentEntity, err := mapper.MapCreateCommentToEntity(&input)
	if err != nil {
		return nil, err
	}

	newComment, err := r.CommentUseCase.Create(ctx, userID, input.ResID, commentEntity)
	if err != nil {
		return nil, err
	}

	commentModel, err := mapper.MapCommentEntityToModel(newComment)
	if err != nil {
		return nil, xerror.Internal("Can not map comment from entity to model")
	}

	return commentModel, nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input model.UpdateCommentInput) (*model.Comment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapUpdateCommentToEntity(&input)
	if err != nil {
		return nil, err
	}

	updatedComment, err := r.CommentUseCase.Update(ctx, userID, input.ResID, input.PostID, input.ID, updateData)
	if err != nil {
		return nil, err
	}

	commentModel, err := mapper.MapCommentEntityToModel(updatedComment)
	if err != nil {
		return nil, xerror.Internal("Can not map comment from entity to model")
	}

	return commentModel, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string, postID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	if err := r.CommentUseCase.Delete(ctx, userID, resID, postID, commentID); err != nil {
		return false, err
	}

	return true, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, commentID string, postID string, resID string) (*model.Comment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	comment, err := r.CommentUseCase.FindByID(ctx, userID, resID, postID, commentID)
	if err != nil {
		return nil, err
	}

	commentModel, err := mapper.MapCommentEntityToModel(comment)
	if err != nil {
		return nil, xerror.Internal("Can not map comment from entity to model")
	}

	return commentModel, nil
}

// CommentsByPost is the resolver for the commentsByPost field.
func (r *queryResolver) CommentsByPost(ctx context.Context, postID string, resID string, limit *int, page *int) (*model.CommentPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	pageValue := 1
	if page != nil {
		pageValue = *page
	}

	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}

	comments, total, err := r.CommentUseCase.FindAllByPostID(ctx, userID, resID, postID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}

	commentPagination, err := mapper.MapCommentsToPagination(comments, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map comments from entity to model")
	}

	return commentPagination, nil
}
