package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateDirectConversation is the resolver for the createDirectConversation field.
func (r *mutationResolver) CreateDirectConversation(ctx context.Context, resID string, targetUserID string) (*model.Conversation, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	conversation, err := r.ConversationUseCase.CreateDirectConversation(ctx, userID, resID, targetUserID)
	if err != nil {
		return nil, err
	}
	conversationModel, err := mapper.MapConversationEntityToModel(conversation)
	if err != nil {
		return nil, xerror.Internal("Can not map conversation from entity to model")
	}
	return conversationModel, nil
}

// CreateGroupConversation is the resolver for the createGroupConversation field.
func (r *mutationResolver) CreateGroupConversation(ctx context.Context, input model.CreateGroupConversationInput) (*model.Conversation, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	conversation, err := r.ConversationUseCase.CreateGroupConversation(ctx, userID, input.ResID, input.Name, input.Avatar, input.ParticipantIDs)
	if err != nil {
		return nil, err
	}
	conversationModel, err := mapper.MapConversationEntityToModel(conversation)
	if err != nil {
		return nil, xerror.Internal("Can not map conversation from entity to model")
	}
	return conversationModel, nil
}

// HideConversation is the resolver for the hideConversation field.
func (r *mutationResolver) HideConversation(ctx context.Context, conversationID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}
	if err := r.ConversationUseCase.HideConversation(ctx, userID, resID, conversationID); err != nil {
		return false, err
	}
	return true, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.Message, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	content := ""
	if input.Content != nil {
		content = *input.Content
	}
	message, err := r.ConversationUseCase.SendMessage(ctx, userID, input.ResID, input.ConversationID, content, input.ImageURL)
	if err != nil {
		return nil, err
	}
	messageModel, err := mapper.MapMessageEntityToModel(message)
	if err != nil {
		return nil, xerror.Internal("Can not map message from entity to model")
	}
	return messageModel, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, conversationID string, resID string) (*model.Conversation, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	conversation, err := r.ConversationUseCase.FindByID(ctx, userID, resID, conversationID)
	if err != nil {
		return nil, err
	}
	conversationModel, err := mapper.MapConversationEntityToModel(conversation)
	if err != nil {
		return nil, xerror.Internal("Can not map conversation from entity to model")
	}
	return conversationModel, nil
}

// MyConversations is the resolver for the myConversations field.
func (r *queryResolver) MyConversations(ctx context.Context, resID string, limit *int, page *int) (*model.ConversationPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	pageValue := 1
	if page != nil {
		pageValue = *page
	}
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}
	conversations, total, err := r.ConversationUseCase.FindAllByUserID(ctx, userID, resID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}
	pagination, err := mapper.MapConversationsToPagination(conversations, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map conversations from entity to model")
	}
	return pagination, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, resID string, limit *int, page *int) (*model.MessagePagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	pageValue := 1
	if page != nil {
		pageValue = *page
	}
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}
	messages, total, err := r.ConversationUseCase.FindMessages(ctx, userID, resID, conversationID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}
	pagination, err := mapper.MapMessagesToPagination(messages, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map messages from entity to model")
	}
	return pagination, nil
}
