package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateFeedback is the resolver for the createFeedback field.
func (r *mutationResolver) CreateFeedback(ctx context.Context, input model.CreateFeedbackInput) (*model.Feedback, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	feedback, err := r.FeedbackUseCase.Create(ctx, userID, input.ResID, input.MemberID, input.Content)
	if err != nil {
		return nil, err
	}
	feedbackModel, err := mapper.MapFeedbackEntityToModel(feedback)
	if err != nil {
		return nil, xerror.Internal("Can not map feedback from entity to model")
	}
	return feedbackModel, nil
}

// UpdateFeedback is the resolver for the updateFeedback field.
func (r *mutationResolver) UpdateFeedback(ctx context.Context, input model.UpdateFeedbackInput) (*model.Feedback, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	feedback, err := r.FeedbackUseCase.Update(ctx, userID, input.ResID, input.ID, input.Content)
	if err != nil {
		return nil, err
	}
	feedbackModel, err := mapper.MapFeedbackEntityToModel(feedback)
	if err != nil {
		return nil, xerror.Internal("Can not map feedback from entity to model")
	}
	return feedbackModel, nil
}

// DeleteFeedback is the resolver for the deleteFeedback field.
func (r *mutationResolver) DeleteFeedback(ctx context.Context, feedbackID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}
	if err := r.FeedbackUseCase.Delete(ctx, userID, resID, feedbackID); err != nil {
		return false, err
	}
	return true, nil
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, feedbackID string, resID string) (*model.Feedback, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	feedback, err := r.FeedbackUseCase.FindByID(ctx, userID, resID, feedbackID)
	if err != nil {
		return nil, err
	}
	feedbackModel, err := mapper.MapFeedbackEntityToModel(feedback)
	if err != nil {
		return nil, xerror.Internal("Can not map feedback from entity to model")
	}
	return feedbackModel, nil
}

// FeedbacksByMember is the resolver for the feedbacksByMember field.
func (r *queryResolver) FeedbacksByMember(ctx context.Context, memberID string, resID string, limit *int, page *int) (*model.FeedbackPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	pageValue := 1
	if page != nil {
		pageValue = *page
	}
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}
	feedbacks, total, err := r.FeedbackUseCase.FindAllByMemberID(ctx, userID, resID, memberID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}
	pagination, err := mapper.MapFeedbacksToPagination(feedbacks, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map feedbacks from entity to model")
	}
	return pagination, nil
}

// FeedbacksByRestaurant is the resolver for the feedbacksByRestaurant field.
func (r *queryResolver) FeedbacksByRestaurant(ctx context.Context, resID string, limit *int, page *int) (*model.FeedbackPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	pageValue := 1
	if page != nil {
		pageValue = *page
	}
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}
	feedbacks, total, err := r.FeedbackUseCase.FindAllByRestaurantID(ctx, userID, resID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}
	pagination, err := mapper.MapFeedbacksToPagination(feedbacks, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map feedbacks from entity to model")
	}
	return pagination, nil
}
