package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreatePosition is the resolver for the createPosition field.
func (r *mutationResolver) CreatePosition(ctx context.Context, input model.CreatePositionInput) (*model.Position, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	positionEntity, err := mapper.MapPositionModelToEntity(&input)
	if err != nil {
		return nil, err
	}

	newPosition, err := r.PositionUseCase.Create(ctx, positionEntity)

	if err != nil {
		return nil, err
	}

	positionModel, err := mapper.MapPositionEntityToModel(newPosition)

	if err != nil {
		return nil, xerror.Internal("Can not map position from entity to model")
	}
	return positionModel, nil
}

// UpdatePosition is the resolver for the updatePosition field.
func (r *mutationResolver) UpdatePosition(ctx context.Context, input model.UpdatePositionInput) (*model.Position, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	updateData, err := mapper.MapUpdatePositionToEntity(&input)

	if err != nil {
		return nil, err
	}

	updatedPosition, err := r.PositionUseCase.Update(ctx, input.ID, userID, input.RestaurantID, updateData)

	if err != nil {
		return nil, err
	}

	positionModel, err := mapper.MapPositionEntityToModel(updatedPosition)

	if err != nil {
		return nil, xerror.Internal("Can not map position from entity to model")
	}

	return positionModel, nil
}

// DeletePosition is the resolver for the deletePosition field.
func (r *mutationResolver) DeletePosition(ctx context.Context, posID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.PositionUseCase.Delete(ctx, userID, resID, posID)

	if err != nil {
		return false, err
	}

	return true, nil
}

// Position is the resolver for the position field.
func (r *queryResolver) Position(ctx context.Context, posID string, resID string) (*model.Position, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	position, err := r.PositionUseCase.FindByID(ctx, posID, userID, resID)

	if err != nil {
		return nil, err
	}

	positionModel, err := mapper.MapPositionEntityToModel(position)
	if err != nil {
		return nil, err
	}
	return positionModel, nil
}

// PositionsByRestaurant is the resolver for the positionsByRestaurant field.
func (r *queryResolver) PositionsByRestaurant(ctx context.Context, resID string) ([]*model.Position, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	positions, err := r.PositionUseCase.GetAllByRestaurantID(ctx, resID, userID)

	if err != nil {
		return nil, err
	}

	positionModel := make([]*model.Position, 0, len(positions))

	for _, position := range positions {
		mappedPosition, err := mapper.MapPositionEntityToModel(position)
		if err != nil {
			return nil, err
		}
		positionModel = append(positionModel, mappedPosition)
	}

	return positionModel, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
