package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	postEntity, err := mapper.MapCreatePostToEntity(&input)
	if err != nil {
		return nil, err
	}

	newPost, err := r.PostUseCase.Create(ctx, userID, input.ResID, postEntity)
	if err != nil {
		return nil, err
	}

	postModel, err := mapper.MapPostEntityToModel(newPost)
	if err != nil {
		return nil, xerror.Internal("Can not map post from entity to model")
	}

	return postModel, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapUpdatePostToEntity(&input)
	if err != nil {
		return nil, err
	}

	updatedPost, err := r.PostUseCase.Update(ctx, userID, input.ResID, input.ID, updateData)
	if err != nil {
		return nil, err
	}

	postModel, err := mapper.MapPostEntityToModel(updatedPost)
	if err != nil {
		return nil, xerror.Internal("Can not map post from entity to model")
	}

	return postModel, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	if err := r.PostUseCase.Delete(ctx, userID, resID, postID); err != nil {
		return false, err
	}

	return true, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, postID string, resID string) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	post, err := r.PostUseCase.FindByID(ctx, userID, resID, postID)
	if err != nil {
		return nil, err
	}

	postModel, err := mapper.MapPostEntityToModel(post)
	if err != nil {
		return nil, xerror.Internal("Can not map post from entity to model")
	}

	return postModel, nil
}

// PostsByRestaurant is the resolver for the postsByRestaurant field.
func (r *queryResolver) PostsByRestaurant(ctx context.Context, resID string, limit *int, page *int) (*model.PostPagination, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	pageValue := 1
	if page != nil {
		pageValue = *page
	}

	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}

	posts, total, err := r.PostUseCase.FindAllByRestaurantID(ctx, userID, resID, pageValue, limitValue)
	if err != nil {
		return nil, err
	}

	postPagination, err := mapper.MapPostsToPagination(posts, total, pageValue, limitValue)
	if err != nil {
		return nil, xerror.Internal("Can not map posts from entity to model")
	}

	return postPagination, nil
}
