package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// ReactToPost is the resolver for the reactToPost field.
func (r *mutationResolver) ReactToPost(ctx context.Context, postID string, resID string, typeArg model.ReactionType) (*model.ReactionResult, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	result, err := r.ReactionUseCase.ReactToPost(ctx, userID, resID, postID, string(typeArg))
	if err != nil {
		return nil, err
	}

	reactionResult, err := mapper.MapReactionResultToModel(result)
	if err != nil {
		return nil, xerror.Internal("Can not map reaction result from entity to model")
	}

	return reactionResult, nil
}

// ReactionsByPost is the resolver for the reactionsByPost field.
func (r *queryResolver) ReactionsByPost(ctx context.Context, postID string, resID string) (*model.ReactionSummary, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	summary, err := r.ReactionUseCase.FindSummaryByPostID(ctx, userID, resID, postID)
	if err != nil {
		return nil, err
	}

	reactionSummary, err := mapper.MapReactionSummaryToModel(summary)
	if err != nil {
		return nil, xerror.Internal("Can not map reaction summary from entity to model")
	}

	return reactionSummary, nil
}
