package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, input model.CreateScheduleInput) (*model.Schedule, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	mappedSchedule, err := mapper.MapScheduleInputToEntity(&input)
	if err != nil {
		return nil, err
	}
	newSchedule, err := r.ScheduleUseCase.Create(ctx, userID, input.RestaurantID, mappedSchedule)

	if err != nil {
		return nil, err
	}
	scheduleModel, err := mapper.MapScheduleEntityToModel(newSchedule)

	if err != nil {
		return nil, err
	}

	return scheduleModel, nil
}

// UpdateSchedule is the resolver for the updateSchedule field.
func (r *mutationResolver) UpdateSchedule(ctx context.Context, input model.UpdateScheduleInput) (*model.Schedule, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapScheduleUpdateToMap(&input)

	if err != nil {
		return nil, err
	}

	updatedSchedule, err := r.ScheduleUseCase.Update(ctx, userID, input.RestaurantID, input.ScheduleID, updateData)

	if err != nil {
		return nil, err
	}

	scheduleModel, err := mapper.MapScheduleEntityToModel(updatedSchedule)

	if err != nil {
		return nil, err
	}

	return scheduleModel, nil
}

// DeleteSchedule is the resolver for the deleteSchedule field.
func (r *mutationResolver) DeleteSchedule(ctx context.Context, resID string, scheID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.ScheduleUseCase.Delete(ctx, userID, resID, scheID)

	if err != nil {
		return false, err
	}

	return true, nil
}

// Schedule is the resolver for the schedule field.
func (r *queryResolver) Schedule(ctx context.Context, scheID string, resID string) (*model.Schedule, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	schedule, err := r.ScheduleUseCase.FindByID(ctx, userID, resID, scheID)

	if err != nil {
		return nil, err
	}

	scheduleModel, err := mapper.MapScheduleEntityToModel(schedule)

	if err != nil {
		return nil, err
	}

	return scheduleModel, nil
}

// AllSchedule is the resolver for the allSchedule field.
func (r *queryResolver) AllSchedule(ctx context.Context, resID string) ([]*model.Schedule, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	schedules, err := r.ScheduleUseCase.FindAllByResID(ctx, userID, resID)

	if err != nil {
		return nil, err
	}

	allSchedule := make([]*model.Schedule, 0, len(schedules))

	for _, schedule := range schedules {
		scheduleModel, err := mapper.MapScheduleEntityToModel(schedule)
		if err != nil {
			return nil, err
		}
		allSchedule = append(allSchedule, scheduleModel)
	}
	return allSchedule, nil
}
