package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateShiftRequest is the resolver for the createShiftRequest field.
func (r *mutationResolver) CreateShiftRequest(ctx context.Context, input model.CreateShiftRequestInput) (*model.ShiftRequest, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	shiftRequestEntity, err := mapper.MapCreateShiftRequestToEntity(&input)
	if err != nil {
		return nil, err
	}

	newShiftRequest, err := r.ShiftRequestUseCase.Create(ctx, userID, input.ResID, input.ShiftID, shiftRequestEntity)
	if err != nil {
		return nil, err
	}

	shiftRequestModel, err := mapper.MapShiftRequestEntityToModel(newShiftRequest)
	if err != nil {
		return nil, xerror.Internal("Can not map shift request from entity to model")
	}

	return shiftRequestModel, nil
}

// UpdateShiftRequest is the resolver for the updateShiftRequest field.
func (r *mutationResolver) UpdateShiftRequest(ctx context.Context, input model.UpdateShiftRequestInput) (*model.ShiftRequest, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapUpdateShiftRequestToEntity(&input)
	if err != nil {
		return nil, err
	}

	updatedShiftRequest, err := r.ShiftRequestUseCase.Update(ctx, userID, input.ResID, input.ShiftID, input.ID, updateData)
	if err != nil {
		return nil, err
	}

	shiftRequestModel, err := mapper.MapShiftRequestEntityToModel(updatedShiftRequest)
	if err != nil {
		return nil, xerror.Internal("Can not map shift request from entity to model")
	}

	return shiftRequestModel, nil
}

// DeleteShiftRequest is the resolver for the deleteShiftRequest field.
func (r *mutationResolver) DeleteShiftRequest(ctx context.Context, requestID string, shiftID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.ShiftRequestUseCase.Delete(ctx, userID, resID, shiftID, requestID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// ShiftRequest is the resolver for the shiftRequest field.
func (r *queryResolver) ShiftRequest(ctx context.Context, requestID string, shiftID string, resID string) (*model.ShiftRequest, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	shiftRequest, err := r.ShiftRequestUseCase.FindByID(ctx, userID, resID, shiftID, requestID)
	if err != nil {
		return nil, err
	}

	shiftRequestModel, err := mapper.MapShiftRequestEntityToModel(shiftRequest)
	if err != nil {
		return nil, err
	}

	return shiftRequestModel, nil
}

// ShiftRequestsByShift is the resolver for the shiftRequestsByShift field.
func (r *queryResolver) ShiftRequestsByShift(ctx context.Context, shiftID string, resID string) ([]*model.ShiftRequest, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	shiftRequests, err := r.ShiftRequestUseCase.FindAllByShiftID(ctx, userID, resID, shiftID)
	if err != nil {
		return nil, err
	}

	shiftRequestModels := make([]*model.ShiftRequest, 0, len(shiftRequests))
	for _, shiftRequest := range shiftRequests {
		mappedShiftRequest, err := mapper.MapShiftRequestEntityToModel(shiftRequest)
		if err != nil {
			return nil, err
		}
		shiftRequestModels = append(shiftRequestModels, mappedShiftRequest)
	}

	return shiftRequestModels, nil
}

// ShiftRequestsByUser is the resolver for the shiftRequestsByUser field.
func (r *queryResolver) ShiftRequestsByUser(ctx context.Context, targetUserID string, resID string) ([]*model.ShiftRequest, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	shiftRequests, err := r.ShiftRequestUseCase.FindAllByUserID(ctx, userID, resID, targetUserID)
	if err != nil {
		return nil, err
	}

	shiftRequestModels := make([]*model.ShiftRequest, 0, len(shiftRequests))
	for _, shiftRequest := range shiftRequests {
		mappedShiftRequest, err := mapper.MapShiftRequestEntityToModel(shiftRequest)
		if err != nil {
			return nil, err
		}
		shiftRequestModels = append(shiftRequestModels, mappedShiftRequest)
	}

	return shiftRequestModels, nil
}
