package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateShiftAssignment is the resolver for the createShiftAssignment field.
func (r *mutationResolver) CreateShiftAssignment(ctx context.Context, input model.CreateShiftAssignmentInput) (*model.ShiftAssignment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	assignmentEntity, err := mapper.MapCreateShiftAssignmentToEntity(&input)
	if err != nil {
		return nil, err
	}

	newAssignment, err := r.ShiftAssignmentUseCase.Create(ctx, userID, input.ResID, input.ShiftID, assignmentEntity)
	if err != nil {
		return nil, err
	}

	assignmentModel, err := mapper.MapShiftAssignmentEntityToModel(newAssignment)
	if err != nil {
		return nil, xerror.Internal("Can not map shift assignment from entity to model")
	}

	return assignmentModel, nil
}

// UpdateShiftAssignment is the resolver for the updateShiftAssignment field.
func (r *mutationResolver) UpdateShiftAssignment(ctx context.Context, input model.UpdateShiftAssignmentInput) (*model.ShiftAssignment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapUpdateShiftAssignmentToEntity(&input)
	if err != nil {
		return nil, err
	}

	updatedAssignment, err := r.ShiftAssignmentUseCase.Update(ctx, userID, input.ResID, input.ShiftID, input.ID, updateData)
	if err != nil {
		return nil, err
	}

	assignmentModel, err := mapper.MapShiftAssignmentEntityToModel(updatedAssignment)
	if err != nil {
		return nil, xerror.Internal("Can not map shift assignment from entity to model")
	}

	return assignmentModel, nil
}

// DeleteShiftAssignment is the resolver for the deleteShiftAssignment field.
func (r *mutationResolver) DeleteShiftAssignment(ctx context.Context, assignmentID string, shiftID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.ShiftAssignmentUseCase.Delete(ctx, userID, resID, shiftID, assignmentID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// ShiftAssignment is the resolver for the shiftAssignment field.
func (r *queryResolver) ShiftAssignment(ctx context.Context, assignmentID string, shiftID string, resID string) (*model.ShiftAssignment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	assignment, err := r.ShiftAssignmentUseCase.FindByID(ctx, userID, resID, shiftID, assignmentID)
	if err != nil {
		return nil, err
	}

	assignmentModel, err := mapper.MapShiftAssignmentEntityToModel(assignment)
	if err != nil {
		return nil, err
	}

	return assignmentModel, nil
}

// ShiftAssignmentsByShift is the resolver for the shiftAssignmentsByShift field.
func (r *queryResolver) ShiftAssignmentsByShift(ctx context.Context, shiftID string, resID string) ([]*model.ShiftAssignment, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	assignments, err := r.ShiftAssignmentUseCase.FindAllByShiftID(ctx, userID, resID, shiftID)
	if err != nil {
		return nil, err
	}

	assignmentModels := make([]*model.ShiftAssignment, 0, len(assignments))
	for _, assignment := range assignments {
		mappedAssignment, err := mapper.MapShiftAssignmentEntityToModel(assignment)
		if err != nil {
			return nil, err
		}
		assignmentModels = append(assignmentModels, mappedAssignment)
	}

	return assignmentModels, nil
}
