package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateShift is the resolver for the createShift field.
func (r *mutationResolver) CreateShift(ctx context.Context, input model.CreateShiftInput) (*model.Shift, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	shiftEntity, err := mapper.MapShiftModelToEntity(&input)
	if err != nil {
		return nil, err
	}

	createdShift, err := r.ShiftUseCase.Create(ctx, userID, input.ResID, shiftEntity)

	if err != nil {
		return nil, err
	}

	shiftModel, err := mapper.MapShiftEntityToModel(createdShift)

	if err != nil {
		return nil, xerror.Internal("Can not map shift from entity to model")
	}
	return shiftModel, nil
}

// UpdateShift is the resolver for the updateShift field.
func (r *mutationResolver) UpdateShift(ctx context.Context, input model.UpdateShiftInput) (*model.Shift, error) {
	userID, ok := ctx.Value("user_id").(string)

	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}
	return nil, nil
}

// DeleteShift is the resolver for the deleteShift field.
func (r *mutationResolver) DeleteShift(ctx context.Context, shiftID string, scheID string, resID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteShift - deleteShift"))
}

// Shift is the resolver for the shift field.
func (r *queryResolver) Shift(ctx context.Context, shiftID string, scheID string, resID string) (*model.Shift, error) {
	panic(fmt.Errorf("not implemented: Shift - shift"))
}

// ShiftsBySchedule is the resolver for the shiftsBySchedule field.
func (r *queryResolver) ShiftsBySchedule(ctx context.Context, scheID string, resID string) ([]*model.Shift, error) {
	panic(fmt.Errorf("not implemented: ShiftsBySchedule - shiftsBySchedule"))
}
