package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"shifty-backend/graph/mapper"
	"shifty-backend/graph/model"
	"shifty-backend/pkg/xerror"
)

// CreateShiftRule is the resolver for the createShiftRule field.
func (r *mutationResolver) CreateShiftRule(ctx context.Context, input model.CreateShiftRuleInput) (*model.ShiftRule, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	ruleEntity, err := mapper.MapCreateShiftRuleToEntity(&input)
	if err != nil {
		return nil, err
	}

	newRule, err := r.ShiftRuleUseCase.Create(ctx, userID, input.ResID, ruleEntity)
	if err != nil {
		return nil, err
	}

	ruleModel, err := mapper.MapShiftRuleEntityToModel(newRule)
	if err != nil {
		return nil, xerror.Internal("Can not map shift rule from entity to model")
	}

	return ruleModel, nil
}

// UpdateShiftRule is the resolver for the updateShiftRule field.
func (r *mutationResolver) UpdateShiftRule(ctx context.Context, input model.UpdateShiftRuleInput) (*model.ShiftRule, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	updateData, err := mapper.MapUpdateShiftRuleToEntity(&input)
	if err != nil {
		return nil, err
	}

	updatedRule, err := r.ShiftRuleUseCase.Update(ctx, userID, input.ResID, updateData, input.ID, input.ResID)
	if err != nil {
		return nil, err
	}

	ruleModel, err := mapper.MapShiftRuleEntityToModel(updatedRule)
	if err != nil {
		return nil, xerror.Internal("Can not map shift rule from entity to model")
	}

	return ruleModel, nil
}

// DeleteShiftRule is the resolver for the deleteShiftRule field.
func (r *mutationResolver) DeleteShiftRule(ctx context.Context, ruleID string, resID string) (bool, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return false, xerror.BadRequest("You are not logged in")
	}

	err := r.ShiftRuleUseCase.Delete(ctx, userID, resID, ruleID, resID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// ShiftRule is the resolver for the shiftRule field.
func (r *queryResolver) ShiftRule(ctx context.Context, ruleID string, resID string) (*model.ShiftRule, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	rule, err := r.ShiftRuleUseCase.FindByID(ctx, userID, resID, ruleID, resID)
	if err != nil {
		return nil, err
	}

	ruleModel, err := mapper.MapShiftRuleEntityToModel(rule)
	if err != nil {
		return nil, err
	}

	return ruleModel, nil
}

// ShiftRulesByRestaurant is the resolver for the shiftRulesByRestaurant field.
func (r *queryResolver) ShiftRulesByRestaurant(ctx context.Context, resID string) ([]*model.ShiftRule, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, xerror.BadRequest("You are not logged in")
	}

	rules, err := r.ShiftRuleUseCase.FindAllByRestaurantID(ctx, userID, resID, resID)
	if err != nil {
		return nil, err
	}

	ruleModels := make([]*model.ShiftRule, 0, len(rules))
	for _, rule := range rules {
		mappedRule, err := mapper.MapShiftRuleEntityToModel(rule)
		if err != nil {
			return nil, err
		}
		ruleModels = append(ruleModels, mappedRule)
	}

	return ruleModels, nil
}
