package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"shifty-backend/graph/model"
)

// CreateShiftRequirement is the resolver for the createShiftRequirement field.
func (r *mutationResolver) CreateShiftRequirement(ctx context.Context, input model.CreateRequirementInput) (*model.ShiftRequirement, error) {
	panic(fmt.Errorf("not implemented: CreateShiftRequirement - createShiftRequirement"))
}

// UpdateShiftRequirement is the resolver for the updateShiftRequirement field.
func (r *mutationResolver) UpdateShiftRequirement(ctx context.Context, input model.UpdateRequirementInput) (*model.ShiftRequirement, error) {
	panic(fmt.Errorf("not implemented: UpdateShiftRequirement - updateShiftRequirement"))
}

// DeleteShiftRequirement is the resolver for the deleteShiftRequirement field.
func (r *mutationResolver) DeleteShiftRequirement(ctx context.Context, reqID string, shiftID string, resID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteShiftRequirement - deleteShiftRequirement"))
}

// ShiftRequirement is the resolver for the shiftRequirement field.
func (r *queryResolver) ShiftRequirement(ctx context.Context, reqID string, shiftID string, resID string) (*model.ShiftRequirement, error) {
	panic(fmt.Errorf("not implemented: ShiftRequirement - shiftRequirement"))
}

// ShiftRequirementsByShift is the resolver for the shiftRequirementsByShift field.
func (r *queryResolver) ShiftRequirementsByShift(ctx context.Context, shiftID string, resID string) ([]*model.ShiftRequirement, error) {
	panic(fmt.Errorf("not implemented: ShiftRequirementsByShift - shiftRequirementsByShift"))
}
