// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	ImageURL  *string    `json:"imageUrl,omitempty"`
	PostID    string     `json:"postID"`
	AuthorID  string     `json:"authorID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Replies   []*Comment `json:"replies"`
	IsDeleted bool       `json:"isDeleted"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type CommentPagination struct {
	Data        []*Comment `json:"data"`
	Total       int        `json:"total"`
	CurrentPage int        `json:"currentPage"`
	TotalPages  int        `json:"totalPages"`
}

type CreateCommentInput struct {
	ResID    string  `json:"resID"`
	PostID   string  `json:"postID"`
	Content  string  `json:"content"`
	ImageURL *string `json:"imageUrl,omitempty"`
	ParentID *string `json:"parentID,omitempty"`
}

type CreateFeedbackInput struct {
	ResID    string `json:"resID"`
	MemberID string `json:"memberID"`
	Content  string `json:"content"`
}

type CreateInviteCodeInput struct {
	Email      string `json:"email"`
	ResID      string `json:"resID"`
	PositionID string `json:"positionID"`
}

type CreatePositionInput struct {
	Name                string `json:"name"`
	Description         string `json:"description"`
	RestaurantID        string `json:"restaurantID"`
	Rank                *int   `json:"rank,omitempty"`
	Salary              *int   `json:"salary,omitempty"`
	CanUpdateRestaurant *bool  `json:"canUpdateRestaurant,omitempty"`
	CanDeleteRestaurant *bool  `json:"canDeleteRestaurant,omitempty"`
}

type CreatePostInput struct {
	ResID    string  `json:"resID"`
	Content  string  `json:"content"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type CreateRequirementInput struct {
	ResID      string    `json:"resID"`
	ShiftID    string    `json:"shiftID"`
	PositionID *string   `json:"positionID,omitempty"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
	Quantity   int       `json:"quantity"`
	Note       *string   `json:"note,omitempty"`
}

type CreateRestaurantInput struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Address     string `json:"address"`
}

type CreateScheduleInput struct {
	StartTime    time.Time `json:"startTime"`
	EndTime      time.Time `json:"endTime"`
	RestaurantID string    `json:"restaurantID"`
}

type CreateShiftAssignmentInput struct {
	ResID        string     `json:"resID"`
	ShiftID      string     `json:"shiftID"`
	UserID       string     `json:"userID"`
	PositionID   *string    `json:"positionID,omitempty"`
	CheckInTime  *time.Time `json:"checkInTime,omitempty"`
	CheckOutTime *time.Time `json:"checkOutTime,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type CreateShiftInput struct {
	ResID           string    `json:"resID"`
	ScheduleID      string    `json:"scheduleID"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	NumberOfMembers int       `json:"numberOfMembers"`
	Type            string    `json:"type"`
	IsHoliday       *bool     `json:"isHoliday,omitempty"`
	WageMultiplier  *float64  `json:"wageMultiplier,omitempty"`
}

type CreateShiftRequestInput struct {
	ResID      string    `json:"resID"`
	ShiftID    string    `json:"shiftID"`
	UserID     string    `json:"userID"`
	PositionID *string   `json:"positionID,omitempty"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
	Note       *string   `json:"note,omitempty"`
}

type CreateShiftRuleInput struct {
	ResID  string `json:"resID"`
	Type   string `json:"type"`
	Name   string `json:"name"`
	Config string `json:"config"`
}

type Feedback struct {
	ID           string     `json:"id"`
	Content      string     `json:"content"`
	RestaurantID string     `json:"restaurantID"`
	MemberID     string     `json:"memberID"`
	ReviewerID   string     `json:"reviewerID"`
	IsDeleted    bool       `json:"isDeleted"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

type FeedbackPagination struct {
	Data        []*Feedback `json:"data"`
	Total       int         `json:"total"`
	CurrentPage int         `json:"currentPage"`
	TotalPages  int         `json:"totalPages"`
}

type JoinRestaurantInput struct {
	InviteCode string `json:"inviteCode"`
}

type Law struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	SeverityLevel string    `json:"severityLevel"`
	Description   string    `json:"description"`
	RestaurantID  string    `json:"restaurantID"`
	CreatedAt     time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Position struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	Rank                int       `json:"rank"`
	Salary              *int      `json:"salary,omitempty"`
	CanUpdateRestaurant bool      `json:"canUpdateRestaurant"`
	CanDeleteRestaurant bool      `json:"canDeleteRestaurant"`
	RestaurantID        string    `json:"restaurantID"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type Post struct {
	ID           string     `json:"id"`
	Content      string     `json:"content"`
	ImageURL     string     `json:"imageUrl"`
	RestaurantID string     `json:"restaurantID"`
	AuthorID     string     `json:"authorID"`
	IsDeleted    bool       `json:"isDeleted"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

type PostPagination struct {
	Data        []*Post `json:"data"`
	Total       int     `json:"total"`
	CurrentPage int     `json:"currentPage"`
	TotalPages  int     `json:"totalPages"`
}

type Query struct {
}

type Reaction struct {
	ID        string       `json:"id"`
	Type      ReactionType `json:"type"`
	PostID    string       `json:"postID"`
	AuthorID  string       `json:"authorID"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type ReactionCount struct {
	Type  ReactionType `json:"type"`
	Count int          `json:"count"`
}

type ReactionResult struct {
	Action   ReactionAction   `json:"action"`
	Reaction *Reaction        `json:"reaction,omitempty"`
	Summary  *ReactionSummary `json:"summary"`
}

type ReactionSummary struct {
	PostID     string           `json:"postID"`
	Total      int              `json:"total"`
	Counts     []*ReactionCount `json:"counts"`
	MyReaction *Reaction        `json:"myReaction,omitempty"`
}

type Restaurant struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Avatar      string      `json:"avatar"`
	Status      bool        `json:"status"`
	Laws        []*Law      `json:"laws,omitempty"`
	Positions   []*Position `json:"positions,omitempty"`
	Members     []*User     `json:"members,omitempty"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type Schedule struct {
	ID              string    `json:"id"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	NumberOfMembers int       `json:"numberOfMembers"`
	NumberOfShifts  int       `json:"numberOfShifts"`
	RestaurantID    string    `json:"restaurantID"`
	CreatedAt       time.Time `json:"createdAt"`
}

type Shift struct {
	ID              string    `json:"id"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	NumberOfMembers int       `json:"numberOfMembers"`
	Type            string    `json:"type"`
	ScheduleID      string    `json:"scheduleID"`
	IsHoliday       bool      `json:"isHoliday"`
	WageMultiplier  float64   `json:"wageMultiplier"`
	IsDeleted       bool      `json:"isDeleted"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type ShiftAssignment struct {
	ID           string     `json:"id"`
	CheckInTime  *time.Time `json:"checkInTime,omitempty"`
	CheckOutTime *time.Time `json:"checkOutTime,omitempty"`
	UserID       string     `json:"userID"`
	ShiftID      string     `json:"shiftID"`
	PositionID   *string    `json:"positionID,omitempty"`
	Note         *string    `json:"note,omitempty"`
	IsDeleted    bool       `json:"isDeleted"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

type ShiftRequest struct {
	ID         string    `json:"id"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
	Status     string    `json:"status"`
	UserID     string    `json:"userID"`
	ShiftID    string    `json:"shiftID"`
	PositionID *string   `json:"positionID,omitempty"`
	Note       *string   `json:"note,omitempty"`
	IsDeleted  bool      `json:"isDeleted"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ShiftRequirement struct {
	ID         string    `json:"id"`
	ShiftID    string    `json:"shiftID"`
	PositionID *string   `json:"positionID,omitempty"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
	Quantity   int       `json:"quantity"`
	Note       *string   `json:"note,omitempty"`
	IsDeleted  bool      `json:"isDeleted"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ShiftRule struct {
	ID           string    `json:"id"`
	Type         string    `json:"type"`
	Name         string    `json:"name"`
	Config       string    `json:"config"`
	IsDeleted    bool      `json:"isDeleted"`
	RestaurantID string    `json:"restaurantID"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type UpdateCommentInput struct {
	ID       string  `json:"id"`
	ResID    string  `json:"resID"`
	PostID   string  `json:"postID"`
	Content  *string `json:"content,omitempty"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type UpdateFeedbackInput struct {
	ID      string `json:"id"`
	ResID   string `json:"resID"`
	Content string `json:"content"`
}

type UpdatePositionInput struct {
	ID                  string  `json:"id"`
	RestaurantID        string  `json:"restaurantID"`
	Name                *string `json:"name,omitempty"`
	Description         *string `json:"description,omitempty"`
	Rank                *int    `json:"rank,omitempty"`
	Salary              *int    `json:"salary,omitempty"`
	CanUpdateRestaurant *bool   `json:"canUpdateRestaurant,omitempty"`
	CanDeleteRestaurant *bool   `json:"canDeleteRestaurant,omitempty"`
}

type UpdatePostInput struct {
	ID       string  `json:"id"`
	ResID    string  `json:"resID"`
	Content  *string `json:"content,omitempty"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type UpdateRequirementInput struct {
	ID         string     `json:"id"`
	ResID      string     `json:"resID"`
	ShiftID    string     `json:"shiftID"`
	PositionID *string    `json:"positionID,omitempty"`
	StartTime  *time.Time `json:"startTime,omitempty"`
	EndTime    *time.Time `json:"endTime,omitempty"`
	Quantity   *int       `json:"quantity,omitempty"`
	Note       *string    `json:"note,omitempty"`
}

type UpdateRestaurantInput struct {
	RestaurantID string  `json:"restaurantID"`
	Name         *string `json:"name,omitempty"`
	Email        *string `json:"email,omitempty"`
	Status       *bool   `json:"status,omitempty"`
	PhoneNumber  *string `json:"phoneNumber,omitempty"`
	Address      *string `json:"address,omitempty"`
}

type UpdateScheduleInput struct {
	RestaurantID string     `json:"restaurantID"`
	ScheduleID   string     `json:"scheduleID"`
	StartTime    *time.Time `json:"startTime,omitempty"`
	EndTime      *time.Time `json:"endTime,omitempty"`
}

type UpdateShiftAssignmentInput struct {
	ID           string     `json:"id"`
	ResID        string     `json:"resID"`
	ShiftID      string     `json:"shiftID"`
	PositionID   *string    `json:"positionID,omitempty"`
	CheckInTime  *time.Time `json:"checkInTime,omitempty"`
	CheckOutTime *time.Time `json:"checkOutTime,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type UpdateShiftInput struct {
	ID              string     `json:"id"`
	ResID           string     `json:"resID"`
	ScheduleID      string     `json:"scheduleID"`
	StartTime       *time.Time `json:"startTime,omitempty"`
	EndTime         *time.Time `json:"endTime,omitempty"`
	NumberOfMembers *int       `json:"numberOfMembers,omitempty"`
	Type            *string    `json:"type,omitempty"`
	IsHoliday       *bool      `json:"isHoliday,omitempty"`
	WageMultiplier  *float64   `json:"wageMultiplier,omitempty"`
}

type UpdateShiftRequestInput struct {
	ID         string     `json:"id"`
	ResID      string     `json:"resID"`
	ShiftID    string     `json:"shiftID"`
	PositionID *string    `json:"positionID,omitempty"`
	StartTime  *time.Time `json:"startTime,omitempty"`
	EndTime    *time.Time `json:"endTime,omitempty"`
	Status     *string    `json:"status,omitempty"`
	Note       *string    `json:"note,omitempty"`
}

type UpdateShiftRuleInput struct {
	ID     string  `json:"id"`
	ResID  string  `json:"resID"`
	Type   *string `json:"type,omitempty"`
	Name   *string `json:"name,omitempty"`
	Config *string `json:"config,omitempty"`
}

type UpdateStaffByManagerInput struct {
	StaffID    *string `json:"staffID,omitempty"`
	Position   *string `json:"position,omitempty"`
	Restaurant *string `json:"restaurant,omitempty"`
	IsBanned   *bool   `json:"isBanned,omitempty"`
}

type UpdateUserInput struct {
	FullName    *string `json:"fullName,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	Position    *string `json:"position,omitempty"`
	Restaurant  *string `json:"restaurant,omitempty"`
}

type User struct {
	ID          string     `json:"id"`
	FullName    string     `json:"fullName"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	Avatar      string     `json:"avatar"`
	PhoneNumber *string    `json:"phoneNumber,omitempty"`
	Address     *string    `json:"address,omitempty"`
	Jobs        []*UserJob `json:"jobs"`
	Status      bool       `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type UserFilterInput struct {
	Search   *string `json:"search,omitempty"`
	Position *string `json:"position,omitempty"`
}

type UserJob struct {
	RestaurantID   string `json:"restaurant_id"`
	RestaurantName string `json:"restaurant_name"`
	Position       string `json:"position"`
}

type UserPagination struct {
	Data        []*User `json:"data"`
	Total       int     `json:"total"`
	CurrentPage int     `json:"currentPage"`
	TotalPages  int     `json:"totalPages"`
}

type UserRestaurant struct {
	UserID     string    `json:"userID"`
	Restaurant string    `json:"restaurant"`
	Position   string    `json:"position"`
	IsBanned   bool      `json:"IsBanned"`
	JoinedAt   time.Time `json:"JoinedAt"`
}

type ReactionAction string

const (
	ReactionActionCreated ReactionAction = "CREATED"
	ReactionActionUpdated ReactionAction = "UPDATED"
	ReactionActionDeleted ReactionAction = "DELETED"
)

var AllReactionAction = []ReactionAction{
	ReactionActionCreated,
	ReactionActionUpdated,
	ReactionActionDeleted,
}

func (e ReactionAction) IsValid() bool {
	switch e {
	case ReactionActionCreated, ReactionActionUpdated, ReactionActionDeleted:
		return true
	}
	return false
}

func (e ReactionAction) String() string {
	return string(e)
}

func (e *ReactionAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReactionAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReactionAction", str)
	}
	return nil
}

func (e ReactionAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReactionAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReactionAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReactionType string

const (
	ReactionTypeLike  ReactionType = "LIKE"
	ReactionTypeLove  ReactionType = "LOVE"
	ReactionTypeCare  ReactionType = "CARE"
	ReactionTypeHaha  ReactionType = "HAHA"
	ReactionTypeWow   ReactionType = "WOW"
	ReactionTypeSad   ReactionType = "SAD"
	ReactionTypeAngry ReactionType = "ANGRY"
)

var AllReactionType = []ReactionType{
	ReactionTypeLike,
	ReactionTypeLove,
	ReactionTypeCare,
	ReactionTypeHaha,
	ReactionTypeWow,
	ReactionTypeSad,
	ReactionTypeAngry,
}

func (e ReactionType) IsValid() bool {
	switch e {
	case ReactionTypeLike, ReactionTypeLove, ReactionTypeCare, ReactionTypeHaha, ReactionTypeWow, ReactionTypeSad, ReactionTypeAngry:
		return true
	}
	return false
}

func (e ReactionType) String() string {
	return string(e)
}

func (e *ReactionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReactionType", str)
	}
	return nil
}

func (e ReactionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReactionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReactionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
