// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreatePositionInput struct {
	Name                string `json:"name"`
	Description         string `json:"description"`
	RestaurantID        string `json:"restaurantID"`
	Rank                *int   `json:"rank,omitempty"`
	Salary              *int   `json:"salary,omitempty"`
	CanUpdateRestaurant *bool  `json:"canUpdateRestaurant,omitempty"`
	CanDeleteRestaurant *bool  `json:"canDeleteRestaurant,omitempty"`
}

type CreateRestaurantInput struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Address     string `json:"address"`
}

type Law struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	SeverityLevel string    `json:"severityLevel"`
	Description   string    `json:"description"`
	RestaurantID  string    `json:"restaurantID"`
	CreatedAt     time.Time `json:"createdAt"`
}

type Mutatio struct {
	Empty *string `json:"_empty,omitempty"`
}

type Mutation struct {
}

type Position struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	Rank                int       `json:"rank"`
	Salary              *int      `json:"salary,omitempty"`
	CanUpdateRestaurant bool      `json:"canUpdateRestaurant"`
	CanDeleteRestaurant bool      `json:"canDeleteRestaurant"`
	RestaurantID        string    `json:"restaurantID"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type Query struct {
}

type Restaurant struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Avatar      string      `json:"avatar"`
	Status      bool        `json:"status"`
	Laws        []*Law      `json:"laws,omitempty"`
	Positions   []*Position `json:"positions,omitempty"`
	Members     []*User     `json:"members,omitempty"`
	PhoneNumber string      `json:"phoneNumber"`
	Address     string      `json:"address"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type UpdatePositionInput struct {
	ID                  string  `json:"id"`
	Name                *string `json:"name,omitempty"`
	Description         *string `json:"description,omitempty"`
	Rank                *int    `json:"rank,omitempty"`
	Salary              *int    `json:"salary,omitempty"`
	CanUpdateRestaurant *bool   `json:"canUpdateRestaurant,omitempty"`
	CanDeleteRestaurant *bool   `json:"canDeleteRestaurant,omitempty"`
}

type UpdateRestaurantInput struct {
	RestaurantID string  `json:"restaurantID"`
	Name         *string `json:"name,omitempty"`
	Email        *string `json:"email,omitempty"`
	Status       *bool   `json:"status,omitempty"`
	PhoneNumber  *string `json:"phoneNumber,omitempty"`
	Address      *string `json:"address,omitempty"`
}

type UpdateStaffByManagerInput struct {
	StaffID    *string `json:"staffID,omitempty"`
	Position   *string `json:"position,omitempty"`
	Restaurant *string `json:"restaurant,omitempty"`
	IsBanned   *bool   `json:"isBanned,omitempty"`
}

type UpdateUserInput struct {
	FullName    *string `json:"fullName,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	Position    *string `json:"position,omitempty"`
	Restaurant  *string `json:"restaurant,omitempty"`
}

type User struct {
	ID          string     `json:"id"`
	FullName    string     `json:"fullName"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	Avatar      string     `json:"avatar"`
	PhoneNumber *string    `json:"phoneNumber,omitempty"`
	Address     *string    `json:"address,omitempty"`
	Jobs        []*UserJob `json:"jobs"`
	Status      bool       `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type UserFilterInput struct {
	Search   *string `json:"search,omitempty"`
	Position *string `json:"position,omitempty"`
}

type UserJob struct {
	RestaurantID   string `json:"restaurant_id"`
	RestaurantName string `json:"restaurant_name"`
	Position       string `json:"position"`
}

type UserPagination struct {
	Data        []*User `json:"data"`
	Total       int     `json:"total"`
	CurrentPage int     `json:"currentPage"`
	TotalPages  int     `json:"totalPages"`
}

type UserRestaurant struct {
	UserID     string    `json:"userID"`
	Restaurant string    `json:"restaurant"`
	Position   string    `json:"position"`
	IsBanned   bool      `json:"IsBanned"`
	JoinedAt   time.Time `json:"JoinedAt"`
}
